'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Toaster } from "sonner";
import { usePathname } from "next/navigation";
import { createContext, useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const outfit = Outfit({ subsets: ["latin"] });
export const UpdateCartContext = createContext();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const [updateCart, setUpdateCart] = useState(false);
  const pathName = usePathname();
  const showHead = pathName == '/sign-up' || pathName == "/sign-in" ? false : true;
  return (
    <PayPalScriptProvider options={{ clientId: 'AXYJS-yVLufrigcox7E3ENUa3A-FvBBi9AfPzIZBNa2zVNC18Yo9RDl7oUYmGe12pUQWU96cjngQPqfq' }}>
      <html lang="en">
        <body className={outfit.className}>
          <UpdateCartContext.Provider value={{ updateCart, setUpdateCart }}>
            {showHead && <Header />}{children}
          </UpdateCartContext.Provider></body>
        <Toaster />
      </html>
    </PayPalScriptProvider>
  );
}
